config/routes.rb
Badminton::Application.routes.draw do
  root :to => 'babies#index'

  resources :babies do
    collection do
      get 'wheres_your_key'
      post 'wheres_your_key'
      post 'select_partner'
      delete 'get_me_out'
    end
  end

  

end

app/models/baby.rb
class Baby < ActiveRecord::Base
  has_one :partner, :class_name => "Baby", :foreign_key => :partner_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def accessible?
    @current_user = session[:current_user]
    if @current_user.blank?
      redirect_to :controller => :babies, :action => :wheres_your_key
    end
  end
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_filter :accessible?, :except => [:wheres_your_key]

  def wheres_your_key
    @invalid_access_code = false
    if request.post?
      access_code = params[:access_code]
      if access_code.blank?
        @invalid_access_code = true

      else
        @baby = Baby.where(access_code: access_code).first
        if @baby.blank?
          @invalid_access_code = true

        else
          puts @baby.inspect
          session[:current_user] = @baby
          redirect_to :action => :index
        end
      end
    end
  end

  def get_me_out
    reset_session
    redirect_to wheres_your_key_babies_url
  end

  # GET /babies
  # GET /babies.json
  def index
    @teams = {}

    babies = Baby.where.not(:team_id => nil)
    babies.each do |baby|
      @teams[baby.team_id] = [] if !@teams.include?(baby.team_id)
      @teams[baby.team_id] << baby
    end
  end

  def select_partner
    if request.post?
      count = random_animal = Baby.where(:gender => @current_user.gender, :partner_id => nil).where.not(id: @current_user.id).count
      random_animal = Baby.where(:gender => @current_user.gender, :partner_id => nil).where.not(id: @current_user.id).first(:offset => rand(count))
      if !random_animal.blank?
        @current_user.partner_id = random_animal.id
        random_animal.partner_id = @current_user.id

        team_id = Baby.maximum(:team_id).to_i
        if team_id.blank?
          team_id = 0
        end
        team_id += 1

        random_animal.team_id = team_id
        @current_user.team_id = team_id

        @current_user.is_selector = true

        random_animal.save()
        @current_user.save()

        response = {status: 'SUCCESS'}
      else
        response = {status: 'ERROR', message: 'No animal available to be your partner. Enjoy your long lonely life!'}
      end
    end

    render :json => response, :layout => false
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def baby_params
      params[:baby]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/views/babies/_form.html.erb
<%= form_for(@baby) do |f| %>
  <% if @baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@baby.errors.count, "error") %> prohibited this baby from being saved:</h2>

      <ul>
      <% @baby.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/babies/edit.html.erb
<h1>Editing baby</h1>

<%= render 'form' %>

<%= link_to 'Show', @baby %> |
<%= link_to 'Back', babies_path %>

app/views/babies/index.html.haml
- if @current_user.gender
  .jumbotron
    .row
      .col-md-12
        %h4 Special animal, please wait for special arrangement (chuckle)
- else
  - if !@current_user.partner_id.blank?
    .jumbotron
      .row
        .col-md-12
          - if @current_user.is_selector
            %h3= "Your partner is [#{@current_user.partner.name}]. Don't fight together!"
          - else
            %h3= "Your lonely life is over! You've chosen by other animal [#{@current_user.partner.name}]."

  - else
    .jumbotron
      .row
        .col-md-12
          %h3.text-center Don't you want to be alone in your Zoo's cage?
          %p.text-center
            = button_tag 'Yes, please give me an animal', :class => 'btn btn-success btn-lg', :id => 'select-partner', :'data-url' => select_partner_babies_url

          %p#message.text-danger.text-center

.row
  .col-md-12
    %table.table.table-striped
      %thead
        %th Cage ID
        %th First Animal
        %th Second Animal
      %tbody
        - if @teams.size > 0
          - @teams.each do |team_id, team|
            %tr
              %td= team_id
              %td
                = team[0].name
                - if team[0].is_selector
                  (*)
              %td
                = team[1].name
                - if team[1].is_selector
                  (*)
        - else
          %tr
            %td{colspan: 3} There is no teams right now!

app/views/babies/new.html.erb
<h1>New baby</h1>

<%= render 'form' %>

<%= link_to 'Back', babies_path %>

app/views/babies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_baby_path(@baby) %> |
<%= link_to 'Back', babies_path %>

app/views/babies/wheres_your_key.html.haml
.jumbotron
  = form_tag wheres_your_key_babies_url(), method: 'post', class: 'form-horizontal', role: 'form' do
    .row
      .col-md-12
        %h3 What is your Zoo ID?
    .row
      .col-md-12
        .input-group{:class => "#{@invalid_access_code ? 'has-error' : ''}"}
          = text_field_tag :access_code, params[:access_code], :autofocus => true, :autocomplete => "off", :class => 'form-control input-lg', :placeholder => "Enter your zoo's number"
          %span.input-group-btn
            = submit_tag "Get access", :class => 'btn btn-success btn-lg'
    .row
      .col-md-12
        %p
          %br/
          %small.smaller Don't have a Zoo ID? Contact Skype [dat.nguyen293] for enrolment.

app/views/layouts/application.html.haml
!!!
%head
  %title Savvycom Open Zoo
  %meta{charset: "utf-8"}
  %meta{:"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
  %meta{:name => 'viewport', :content => "width=device-width, initial-scale=1"}

  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags

  / Latest compiled and minified CSS
  %link{:rel => "stylesheet", :href => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"}

  / Optional theme
  %link{:rel => "stylesheet", :href => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css"}

  / Latest compiled and minified JavaScript
  %script{:src => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js", :type => "text/javascript"}

%body
  .navbar.navbar-inverse{:role => "navigation"}
    .container
      .navbar-header
        = link_to 'Savvycom Open Zoo', '#', :class => "navbar-brand"

      - if !@current_user.blank?
        %ul.nav.navbar-nav.pull-right
          %li.dropdown
            = link_to '#', :class => 'dropdown-toggle', :'data-toggle' => 'dropdown' do
              = @current_user.name
              %b.caret
            %ul.dropdown-menu
              %li= link_to 'Logout', get_me_out_babies_url, :'data-method' => 'delete'

  .container.theme-showcase{role: 'main'}
    = yield